name: test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        go-version: ["^1.22"]
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Start SurrealDB
        run: docker run -it -d --rm --name surrealdb -p 8000:8000 surrealdb/surrealdb:nightly start -u root -p root
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache-dependency-path: go.sum
      - name: test
        run: go test -v -cover ./...
        env:
          SURREALDB_URL: ws://localhost:8000/rpc
      - name: Stop SurrealDB
        if: always()
        run: docker stop -t 1 surrealdb
